### ISSUE TITLE
Social media links links to nowhere

### ISSUE THREAD

**Issue by Pawat-Sarnchawanakit** [Pong50887/RentHub-Connect#143]
Clicking on these just go to the beginning of the current page
![image](https://github.com/user-attachments/assets/55bf2c36-15b8-488f-bd3d-c97c715dac76)

**Comment by NewOsakA** [comment]
I must say that this is intentional, as explained during the demo presentation. Since the app is designed for apartment property owners, the hyperlinks are meant to be placeholders to be filled later. However, I have added sample links for demonstration purposes.
