### ISSUE TITLE
I can upload any type of file as payment slips

### ISSUE THREAD

**Issue by OmegaOoh** [Pong50887/RentHub-Connect#144]
![image](https://github.com/user-attachments/assets/50d81198-b4df-405e-9d73-7a91800d8307)

Fun fact I can read the file that returns from the slips (on the history page)

![image](https://github.com/user-attachments/assets/627c177a-8f04-45e2-a044-fe05ae1f35fd)

## How to reproduce
1. Visit the and try to rent something
2. Upload Any type of file as payment slips

**Comment by Thanawas-Sirilertsathit** [comment]
💀 💀 💀💀 💀 💀💀 💀 💀

**Comment by Thanawas-Sirilertsathit** [comment]
![image](https://github.com/user-attachments/assets/53263278-e578-4f00-8738-b71cd68ed3ac)

**Comment by Thanawas-Sirilertsathit** [comment]
![image](https://github.com/user-attachments/assets/304450d2-c4c3-403c-8e2c-63892521811d)

**Comment by PHIMNADA024** [comment]
Thank you for letting us know! We will address this issue to improve the website.

**Comment by OmegaOoh** [comment]
You close the issues but I can still upload random files as payment slips. By doing this you'll lose track of how many issues were fixed and how many weren't.  Please reopen the unfixed issues. By the way, You should at least have a constraint in HTML input which you can find how to do it [here](https://www.w3schools.com/TAGS/att_input_accept.asp).

**Comment by PHIMNADA024** [comment]
Apologies for not updating you earlier. I’ve already fixed this issue, but the changes are currently committed to the bugFix branch and haven’t been merged into the main branch yet, so the updates aren’t reflected on the live site.
