### ISSUE TITLE
Your filter dies if the filter keyword is too large

### ISSUE THREAD

**Issue by KhunakornP** [Pong50887/RentHub-Connect#145]
## **Bug**
If the filter is too large the site returns 414 URI too large

## **How To Reproduce**
1. Go to rooms
2. Use some large filter like `https://renthubconnect.onrender.com/room/https://renthubconnect.onrender.com/room/https://renthubconnect.onrender.com/room/https://renthubconnect.onrender.com/room/https://renthubconnect.onrender.com/room/https://renthubconnect.onrender.com/room/https://renthubconnect.onrender.com/room/https://renthubconnect.onrender.com/room/https://renthubconnect.onrender.com/room/https://renthubconnect.onrender.com/room/https://renthubconnect.onrender.com/room/https://renthubconnect.onrender.com/room/https://renthubconnect.onrender.com/room/https://renthubconnect.onrender.com/room/https://renthubconnect.onrender.com/room/https://renthubconnect.onrender.com/room/https://renthubconnect.onrender.com/room/`
more lines omitted...
or
`Double Bed Room - Room 106Double Bed Room - Room 106Double Bed Room - Room 106Double Bed Room - Room 106Double Bed Room - Room 106Double Bed Room - Room 106Double Bed Room - Room 106Double Bed Room - Room 106Double Bed Room - Room 106Double Bed Room - Room 106Double Bed Room - Room 106Double Bed Room - Room 106Double Bed Room - Room 106Double Bed Room - Room 106Double Bed Room - Room 106Double Bed Room - Room 106Double Bed Room - Room 106Double Bed Room - Room 106Double Bed Room - Room 106Double Bed Room - Room 106Double Bed Room - Room 106Double Bed Room - Room 106Double Bed Room - Room 106Double Bed Room - Room 106Double Bed Room - Room 106`
more lines omitted...

## **User Specifications**
OS: Windows 10
Browser: Chrome Version 131.0.6778.86

## **Screenshots**
![fe2](https://github.com/user-attachments/assets/576e8c13-5174-4246-bd40-e04733b81b62)
![filter error](https://github.com/user-attachments/assets/9d2a3718-74eb-4d91-8cdf-6dfbe88d551e)

**Comment by KhunakornP** [comment]
## **Follow up**
It also dies if you filter for a room type that does not exist
`https://renthubconnect.onrender.com/room/?search=&room_type=SELECT * FROM *`
[url](https://renthubconnect.onrender.com/room/?search=&room_type=SELECT%20*%20FROM%20*)

**Comment by PHIMNADA024** [comment]
Thank you for letting us know! We will address this issue to improve the website.
