### ISSUE TITLE
When no rooms are available the site does not notify the user

### ISSUE THREAD

**Issue by KhunakornP** [Pong50887/RentHub-Connect#146]
## **Bug**
When trying to find a room type and no rooms are available the page displays "Rooms of Type:"

## **How To Reproduce**
1. Go to queen sized bedroom
2. Assuming that all rooms are booked you should see the screenshot

## **Screenshots**

![no rooms](https://github.com/user-attachments/assets/2d112e53-3a68-4b64-9bf8-76aaf4c091a2)

## **User Specifications**
OS: Windows 10
Browser: Chrome Version 131.0.6778.86

**Comment by Pong50887** [comment]
Thanks for the advice, we fixed it and released it in branch 'bugFix'.
