### ISSUE TITLE
Phone Number Field Allows Non-Numeric Input

### ISSUE THREAD

**Issue by colarrbear** [Pong50887/RentHub-Connect#148]
In the phone number field of the form, I’m unsure why I am able to enter string instead of just number.
<br>
While it makes sense to store phone numbers as strings or in a VARCHAR format, it would be beneficial to restrict user input in that field. Ideally, users should only be able to enter numeric characters or leave the field blank. This would help ensure data integrity and improve the overall user experience.

<img width="1710" alt="image" src="https://github.com/user-attachments/assets/a009b3c9-63d8-460e-841b-5c93df1cf8e1">

[Using in MacOS 14.6.1 with Arc Browser]

**Comment by Karczel** [comment]
Thank you! I will try to restrict to only numeric with regex

**Comment by Karczel** [comment]
Done! please wait until we merge bugFix and re-deploy to check again
