### ISSUE TITLE
Renter can rent a room many times by pressing Send button many times

### ISSUE THREAD

**Issue by Thanawas-Sirilertsathit** [Pong50887/RentHub-Connect#150]
Expected behavior : During press Send button and it is loading in renting room page. It should disable the button or somehow prevent user from create many renting objects.
Current behavior : The Send button allows renter to create many rent objects using the same set of data by using the gap when it is processing.
Step to reproduce : 
1. Select the room
2. Go to rent page of that room
3. Fill in the payment slip
4. Press the send button
5. During website is loading press it repeatedly (Try in many time intervals) Sometimes it does create multiple object.
6. If it does not work, try js injection in <script> 
```
javascript:(function(){const button=document.querySelector('button.btn.btn-primary');function simulateClick(){button.click();}for(let i=0;i<100;i++){simulateClick();}})();
```

* Also the datetime is UTC time why don't you show it as local time
With JS Injection
<img width="936" alt="image" src="https://github.com/user-attachments/assets/c5897d12-ee7e-41f1-9afd-b8a47b770641">
Without JS Injection
<img width="941" alt="image" src="https://github.com/user-attachments/assets/d0b95c63-555c-4b9a-a49a-e571e4c3ec93">

**Comment by Thanawas-Sirilertsathit** [comment]
Please add more rooms. There are no rooms for testing in production server now.

**Comment by Thanawas-Sirilertsathit** [comment]
<img width="959" alt="image" src="https://github.com/user-attachments/assets/d6689403-f29c-4104-a909-3906f147d1b5">

**Comment by Pong50887** [comment]
Thanks for the advice, we fixed it and released in the branch name 'bugFix'
